# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jeweler/all/jeweler.rbi
#
# jeweler-2.3.9

class Jeweler
  def base_dir; end
  def base_dir=(arg0); end
  def build_gem; end
  def bump_major_version; end
  def bump_minor_version; end
  def bump_patch_version; end
  def check_dependencies(type = nil); end
  def commit; end
  def commit=(arg0); end
  def expects_version_file?; end
  def gemspec; end
  def gemspec_helper; end
  def git_base_dir(base_dir = nil); end
  def in_git_repo?; end
  def initialize(gemspec, base_dir = nil); end
  def install_gem; end
  def major_version; end
  def minor_version; end
  def output; end
  def output=(arg0); end
  def patch_version; end
  def release_gem_to_rubyforge; end
  def release_gem_to_rubygems; end
  def release_gemspec(args); end
  def release_to_git(args); end
  def repo; end
  def repo=(arg0); end
  def setup_rubyforge; end
  def valid_gemspec?; end
  def validate_gemspec; end
  def version; end
  def version_file_exist?; end
  def version_helper; end
  def write_gemspec; end
  def write_version(major, minor, patch, build, _options = nil); end
end
module Jeweler::Version
end
class Jeweler::GemspecError < StandardError
end
class Jeweler::VersionYmlError < StandardError
end
