# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mutex_m` gem.
# Please instead update this file by running `bin/tapioca gem mutex_m`.


module Mutex_m
  def initialize(*args, **_arg1); end

  def mu_extended; end
  def mu_lock; end
  def mu_locked?; end
  def mu_synchronize(&block); end
  def mu_try_lock; end
  def mu_unlock; end
  def sleep(timeout = T.unsafe(nil)); end

  private

  def mu_initialize; end

  class << self
    def append_features(cl); end
    def define_aliases(cl); end
    def extend_object(obj); end
    def prepend_features(cl); end
  end
end

Mutex_m::VERSION = T.let(T.unsafe(nil), String)
