# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rackup` gem.
# Please instead update this file by running `bin/tapioca gem rackup`.


module Rackup; end
Rackup::VERSION = T.let(T.unsafe(nil), String)
