# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `securerandom` gem.
# Please instead update this file by running `bin/tapioca gem securerandom`.


module SecureRandom
  extend ::Random::Formatter

  class << self
    def bytes(n); end
    def gen_random(n); end

    private

    def gen_random_openssl(n); end
    def gen_random_urandom(n); end
  end
end

SecureRandom::VERSION = T.let(T.unsafe(nil), String)
