inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-sorbet

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'lib/generators/acts_as_messageable/migration/templates/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Style/OptionalBooleanParameter:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Naming/FileName:
  Exclude:
    - 'lib/acts-as-messageable.rb'

