inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'lib/generators/acts_as_messageable/migration/templates/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Naming/FileName:
  Exclude:
    - 'lib/acts-as-messageable.rb'
