# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts-as-messageable}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Piotr Nielacny"]
  s.date = %q{2010-08-10}
  s.email = %q{piotr.nielacny@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/acts-as-messageable.rb",
     "lib/acts_as_messageable/acts-as-messageable.rb",
     "lib/acts_as_messageable/message.rb",
     "lib/generators/acts_as_messageable/migration/migration_generator.rb",
     "lib/generators/acts_as_messageable/migration/templates/migration.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/LTe/acts_as_messageable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Make user messageable!;-)}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

