# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ActionDispatch::Response::ContentTypeHeader; end
module PG::TextDecoder::TimestampLocal; end
module PG::TypeMap::DefaultTypeMappable; end
module Rails::SourceAnnotationExtractor; end
module T::CompatibilityPatches::RSpecCompatibility::MethodDoubleExtensions; end
module T::CompatibilityPatches::RSpecCompatibility::RecorderExtensions; end
