name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    strategy:
      matrix:
        include:
          - rvm: 2.3.8
            gemfile: gemfiles/rails_3.2.gemfile
          - rvm: 2.3.8
            gemfile: gemfiles/rails_4.2.gemfile
          - rvm: 2.7
            gemfile: gemfiles/rails_5.2.gemfile
          - rvm: 2.7
            gemfile: gemfiles/rails_6.0.gemfile
          - rvm: 2.7
            gemfile: gemfiles/rails_5.2.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.rvm }}
          bundler-cache: true
      - run: bundle exec rake
